### ISSUE TITLE
Quick Start Returns [404 Not Found]

### ISSUE THREAD

**Issue by marcelocorni** [sisk-http/quickstart#1]
Sample from Quick Start from documentaton returns [404 Not Found]

**Comment by CypherPotato** [comment]
Hello.

Which quickstarter project are you running? And with what URL are you trying to access the Sisk application after running the quickstarter?

Thank you.

**Comment by CypherPotato** [comment]
Issue closed due to lack of details. Feel free to comment here and give more details to reopen the issue.
